In [1]:
using Oscar

  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.1.0


# The tropical Grassmannian TGr$(3,6)$

Author: Michael Joswig

The Grassmannian Gr$(k,n)$ is an algebraic variety which parametrizes the $k$-dimensional linear subspaces of an $n$-dimensional vector space, say over the complex numbers.
The tropical Grassmannian TGr$(k,n)$ is its tropicalization, and it parametrizes the realizable tropical linear spaces.

The investigation of the tropical Grassmannians started with [an article](https://www.degruyter.com/document/doi/10.1515/advg.2004.023/pdf) by Speyer and Sturmfels.
Here we recover some of their results.

We begin with loading the output for TGr$(3,6)$ of a [computation](https://www.sciencedirect.com/science/article/pii/S0747717123000317) by Bendle, Böhm, Ren and Schröter.
That output employs the [MaRDI file format](https://arxiv.org/abs/2309.00465) developed by Della Vecchia, Joswig and Lorenz.
In the original Speyer-Sturmfels paper Jensen's software [GFan](https://users-math.au.dk/jensen/software/gfan/gfanmanual0.6.pdf) was used.

In [2]:
TGr36 = load("TGr36.mrdi")

Polyhedral fan in ambient dimension 20

The ambient dimension is $\tbinom{n}{k}=20$, but the tropical Grassmannian is smaller.
By the way, here we follow the max convention.

In [3]:
dim(TGr36)

10

And it has an $n$-dimensional lineality space.

In [4]:
lineality_dim(TGr36)

6

The following output lists the number of cones per dimension.  The lineality space occurs as a list of initial zeros.

In [5]:
show(f_vector(TGr36))

ZZRingElem[0, 0, 0, 0, 0, 0, 65, 550, 1395, 1035]

We are interested in the topology of the spherical polytopal complex obtained by intersection the fan with the unit sphere.
Up to homotopy this can be read off the incidences between the maximal cones and the rays.

In [6]:
K = simplicial_complex(maximal_cones(IncidenceMatrix, TGr36))

Abstract simplicial complex of dimension 3 on 65 vertices

Of course, we loose one dimension from $10-6=4$ in the process.

In [7]:
dim(K)

3

The $f$-vector is still the same (except for those zeros), because TGr$(3,6)$ is simplicial.

In [8]:
show(f_vector(K))

[65, 550, 1395, 1035]

The homology is concentrated in the top dimension.

In [9]:
[ homology(K, i) for i in 0:3 ]

4-element Vector{FinGenAbGroup}:
 Z
 Z/1
 Z/1
 Z^126

## Tropical linear spaces

The tropical Grassmannin TGr$(3,6)$ parameterizes tropical planes in the tropical projective torus $\mathbb{R}^6/\mathbb{R}1$.
We tropicalize with respect to the $5$-adic valuation.

In [10]:
nu = tropical_semiring_map(QQ, 5, max)

Map into Max tropical semiring encoding the 5-adic valuation on Rational field

Here is a (rational) matrix, whose row space forms a $2$-dimensional subspace of $\mathbb{P}^5$.

In [11]:
A = matrix(QQ, [1 0 0 1 5 25; 0 1 0 1//125 1//625 2//5; 0 0 1 -5 -27 -124])

[1   0   0        1        5     25]
[0   1   0   1//125   1//625   2//5]
[0   0   1       -5      -27   -124]

By tropicalizing the maximal minors we get a tropical Plücker vector.

In [12]:
pi = [ QQ(nu.(det(A[:, sigma]))) for sigma in sort(subsets(6,3)) ];
show(pi)

QQFieldElem[0, -1, 0, 0, 3, 4, 1, 3, 3, 4, 0, -1, -2, 0, 0, -1, 4, 1, 2, 4]

Since we ordered the coordinates of the (tropical) Plücker vector in the same way as the coordinates were chosen for TGr$(3,6)$, we can now find the maximal cones containing $\pi$.

In [13]:
i = 0

for C in maximal_cones(TGr36)
    i += 1
    if (in(pi, C))
        print(i, " ")
    end
end

674 777 780 826 837 934 938 970 1018 1022 

For simplicity here we only print ids.